# syntax=docker/dockerfile:1.3.1
ARG LEADER_HOST

FROM node:18-alpine
WORKDIR /app
COPY . .

# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --upgrade pip setuptools

# Run app
ENV LEADER_HOST=${LEADER_HOST}
RUN python3 -m pip install -r requirements.txt
CMD ["python3", "leader.py"]
EXPOSE 5001